Repository AssemblyScript/assemblyscript, pull requests merged in 2020-10, with the labels that each got.

#1484 Add bultins: i32/i64/f32/f64.add/sub/mul
  NOTICE
  src/builtins.ts
  std/assembly/builtins.ts
  std/assembly/index.d.ts
  tests/compiler/builtins.optimized.wat
  tests/compiler/builtins.ts
  tests/compiler/builtins.untouched.wat
Labels: compatibility, enhancement

#1481 Update binaryen again
  package-lock.json
  package.json
  src/glue/binaryen.d.ts
  src/module.ts
  tests/compiler/do.optimized.wat
  tests/compiler/extends-baseaggregate.optimized.wat
  tests/compiler/for.optimized.wat
  tests/compiler/implicit-getter-setter.optimized.wat
  tests/compiler/issues/1095.optimized.wat
  tests/compiler/issues/1225.optimized.wat
  tests/compiler/logical.optimized.wat
  tests/compiler/managed-cast.optimized.wat
  tests/compiler/object-literal.optimized.wat
  tests/compiler/rc/local-init.optimized.wat
  tests/compiler/rc/logical-and-mismatch.optimized.wat
  tests/compiler/rc/logical-or-mismatch.optimized.wat
  tests/compiler/rc/optimize.optimized.wat
  tests/compiler/rc/rereturn.optimized.wat
  tests/compiler/rc/ternary-mismatch.optimized.wat
  tests/compiler/resolve-ternary.optimized.wat
  tests/compiler/retain-release-sanity.optimized.wat
  tests/compiler/retain-return.optimized.wat
  tests/compiler/rt/finalize.optimized.wat
  tests/compiler/runtime-full.optimized.wat
  tests/compiler/std/array-literal.optimized.wat
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/arraybuffer.optimized.wat
  tests/compiler/std/dataview.optimized.wat
  tests/compiler/std/map.optimized.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/set.optimized.wat
  tests/compiler/std/staticarray.optimized.wat
  tests/compiler/std/string-casemapping.optimized.wat
  tests/compiler/std/string-encoding.optimized.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/while.optimized.wat
Labels: dependencies, enhancement, performance

#1494 fix(compiler): Implement proper left / right cyclic builtin rotation for small integers
  src/builtins.ts
  tests/compiler/builtins.optimized.wat
  tests/compiler/builtins.ts
  tests/compiler/builtins.untouched.wat
Labels: compatibility, enhancement, standard library

#1475 improve inlining thresholds for default optimization
  src/module.ts
  tests/compiler/assert-nonnull.optimized.wat
  tests/compiler/binary.optimized.wat
  tests/compiler/builtins.optimized.wat
  tests/compiler/call-optional.optimized.wat
  tests/compiler/class-implements.optimized.wat
  tests/compiler/class-overloading.optimized.wat
  tests/compiler/do.optimized.wat
  tests/compiler/extends-baseaggregate.optimized.wat
  tests/compiler/field-initialization.optimized.wat
  tests/compiler/for.optimized.wat
  tests/compiler/function-expression.optimized.wat
  tests/compiler/function-types.optimized.wat
  tests/compiler/if.optimized.wat
  tests/compiler/implicit-getter-setter.optimized.wat
  tests/compiler/infer-array.optimized.wat
  tests/compiler/infer-generic.optimized.wat
  tests/compiler/logical.optimized.wat
  tests/compiler/managed-cast.optimized.wat
  tests/compiler/many-locals.optimized.wat
  tests/compiler/number.optimized.wat
  tests/compiler/object-literal.optimized.wat
  tests/compiler/rc/logical-and-mismatch.optimized.wat
  tests/compiler/rc/logical-or-mismatch.optimized.wat
  tests/compiler/rc/optimize.optimized.wat
  tests/compiler/rc/rereturn.optimized.wat
  tests/compiler/rc/ternary-mismatch.optimized.wat
  tests/compiler/resolve-access.optimized.wat
  tests/compiler/resolve-binary.optimized.wat
  tests/compiler/resolve-elementaccess.optimized.wat
  tests/compiler/resolve-function-expression.optimized.wat
  tests/compiler/resolve-propertyaccess.optimized.wat
  tests/compiler/resolve-ternary.optimized.wat
  tests/compiler/resolve-unary.optimized.wat
  tests/compiler/retain-release-sanity.optimized.wat
  tests/compiler/retain-return.optimized.wat
  tests/compiler/rt/finalize.optimized.wat
  tests/compiler/rt/instanceof.optimized.wat
  tests/compiler/std/array-access.optimized.wat
  tests/compiler/std/array-literal.optimized.wat
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/arraybuffer.optimized.wat
  tests/compiler/std/dataview.optimized.wat
  tests/compiler/std/map.optimized.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/object.optimized.wat
  tests/compiler/std/operator-overloading.optimized.wat
  tests/compiler/std/set.optimized.wat
  tests/compiler/std/staticarray.optimized.wat
  tests/compiler/std/string-casemapping.optimized.wat
  tests/compiler/std/string-encoding.optimized.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/symbol.optimized.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/super-inline.optimized.wat
  tests/compiler/typeof.optimized.wat
  tests/compiler/wasi/abort.optimized.wat
  tests/compiler/wasi/trace.optimized.wat
  tests/compiler/while.optimized.wat
Labels: enhancement, performance

#1498 Slightly improve pass pipeline
  src/module.ts
  tests/compiler/issues/1095.optimized.wat
  tests/compiler/retain-release-sanity.optimized.wat
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/map.optimized.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/set.optimized.wat
  tests/compiler/std/string-casemapping.optimized.wat
  tests/compiler/std/string-encoding.optimized.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/symbol.optimized.wat
  tests/compiler/std/typedarray.optimized.wat
Labels: enhancement, performance

#1489 Refactor binary expression compilation to be reusable in builtins
  src/builtins.ts
  src/compiler.ts
Labels: enhancement

#1506 Update binaryen to latest
  package-lock.json
  package.json
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/string-casemapping.optimized.wat
Labels: dependencies, performance

#1511 fix(compiler): wrap RHS shifting value by maximum size of type in bits for small integers
  src/compiler.ts
  tests/compiler/abi.untouched.wat
  tests/compiler/retain-i32.ts
  tests/compiler/retain-i32.untouched.wat
  tests/compiler/std/dataview.untouched.wat
  tests/compiler/std/polyfills.untouched.wat
Labels: breaking change, enhancement

#1514 Update binaryen
  package-lock.json
  package.json
Labels: dependencies

#1513 Make loader ESM by default, with UMD fallback
  .eslintrc.js
  .github/workflows/publish.yml
  .github/workflows/test.yml
  cli/asc.js
  lib/loader/index.js
  lib/loader/package.json
  lib/loader/tests/index.js
  lib/loader/tests/umd/index.js
  lib/loader/tests/umd/package.json
  lib/loader/umd/index.d.ts
  lib/loader/umd/index.js
  lib/loader/umd/package.json
  package.json
  tests/asconfig/index.js
  tests/bootstrap/index.ts
  tests/bootstrap/package.json
Labels: breaking change, enhancement, tooling

#1515 Make Rtrace ESM by default, with UMD fallback
  lib/rtrace/README.md
  lib/rtrace/index.d.ts
  lib/rtrace/index.js
  lib/rtrace/package.json
  lib/rtrace/umd/index.d.ts
  lib/rtrace/umd/index.js
  lib/rtrace/umd/package.json
  package.json
  tests/bootstrap/index.ts
  tests/compiler.js
Labels: breaking change, enhancement, tooling

#1520 Update to latest binaryen
  package-lock.json
  package.json
  tests/compiler/number.optimized.wat
  tests/compiler/resolve-binary.optimized.wat
  tests/compiler/resolve-ternary.optimized.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/mod.optimized.wat
  tests/compiler/std/typedarray.optimized.wat
Labels: dependencies

#1523 Update binaryen
  package-lock.json
  package.json
  tests/compiler/std/string-casemapping.optimized.wat
  tests/compiler/std/string.optimized.wat
Labels: dependencies, enhancement

#1521 Slightly optimize Math.mod
  std/assembly/math.ts
  tests/compiler/binary.untouched.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/math.untouched.wat
  tests/compiler/std/mod.optimized.wat
  tests/compiler/std/mod.untouched.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/std/typedarray.untouched.wat
Labels: enhancement, standard library

#1525 Fix string casemapping test
  tests/compiler/std/string-casemapping.optimized.wat
  tests/compiler/std/string-casemapping.ts
  tests/compiler/std/string-casemapping.untouched.wat
Labels: standard library, tooling

#1528 Add link to examples in readme.md
  README.md
Labels: enhancement, meta

#1526 Update binaryen. Slightly improve pass pipeline
  package-lock.json
  package.json
  src/module.ts
  tests/compiler/extends-baseaggregate.optimized.wat
  tests/compiler/memmove.optimized.wat
  tests/compiler/retain-release-sanity.optimized.wat
  tests/compiler/retain-return.optimized.wat
  tests/compiler/std/array-literal.optimized.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/mod.optimized.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/typedarray.optimized.wat
Labels: dependencies, enhancement
