Repository AssemblyScript/assemblyscript, pull requests merged in 2020-03, with the labels that each got.

#1160 optimize decimalCount32/64 + minor refactoring in util/number
  std/assembly/util/number.ts
  tests/compiler/number.optimized.wat
  tests/compiler/number.untouched.wat
  tests/compiler/resolve-access.optimized.wat
  tests/compiler/resolve-access.untouched.wat
  tests/compiler/resolve-binary.optimized.wat
  tests/compiler/resolve-binary.untouched.wat
  tests/compiler/resolve-elementaccess.optimized.wat
  tests/compiler/resolve-elementaccess.untouched.wat
  tests/compiler/resolve-function-expression.optimized.wat
  tests/compiler/resolve-function-expression.untouched.wat
  tests/compiler/resolve-propertyaccess.optimized.wat
  tests/compiler/resolve-propertyaccess.untouched.wat
  tests/compiler/resolve-ternary.optimized.wat
  tests/compiler/resolve-ternary.untouched.wat
  tests/compiler/resolve-unary.optimized.wat
  tests/compiler/resolve-unary.untouched.wat
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/array.untouched.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/string.untouched.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/std/typedarray.untouched.wat
Labels: performance

#1159 Add WASI abort, trace and seed implementations
  cli/asc.js
  lib/loader/index.js
  src/builtins.ts
  src/common.ts
  src/compiler.ts
  src/program.ts
  std/assembly/bindings/wasi_snapshot_preview1.ts
  std/assembly/bindings/wasi_unstable.ts
  std/assembly/builtins.ts
  std/assembly/index.d.ts
  std/assembly/math.ts
  std/assembly/string.ts
  std/assembly/wasi/index.ts
  tests/compiler.js
  tests/compiler/features/mutable-globals.js
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/array.untouched.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/math.untouched.wat
  tests/compiler/std/string-encoding.optimized.wat
  tests/compiler/std/string-encoding.untouched.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/wasi/abort.js
  tests/compiler/wasi/abort.json
  tests/compiler/wasi/abort.optimized.wat
  tests/compiler/wasi/abort.ts
  tests/compiler/wasi/abort.untouched.wat
  tests/compiler/wasi/seed.js
  tests/compiler/wasi/seed.json
  tests/compiler/wasi/seed.optimized.wat
  tests/compiler/wasi/seed.ts
  tests/compiler/wasi/seed.untouched.wat
  tests/compiler/wasi/snapshot_preview1.json
  tests/compiler/wasi/snapshot_preview1.optimized.wat
  tests/compiler/wasi/snapshot_preview1.ts
  tests/compiler/wasi/snapshot_preview1.untouched.wat
  tests/compiler/wasi/trace.js
  tests/compiler/wasi/trace.json
  tests/compiler/wasi/trace.optimized.wat
  tests/compiler/wasi/trace.ts
  tests/compiler/wasi/trace.untouched.wat
Labels: breaking change

#1121 Decouple Array<T> from ArrayBufferView
  lib/loader/index.js
  lib/loader/tests/build/default.wasm
  lib/loader/tests/build/legacy.wasm
  src/builtins.ts
  src/program.ts
  std/assembly/array.ts
  tests/compiler/assert-nonnull.optimized.wat
  tests/compiler/assert-nonnull.untouched.wat
  tests/compiler/builtins.optimized.wat
  tests/compiler/builtins.untouched.wat
  tests/compiler/class.optimized.wat
  tests/compiler/class.untouched.wat
  tests/compiler/extends-baseaggregate.optimized.wat
  tests/compiler/extends-baseaggregate.untouched.wat
  tests/compiler/infer-array.optimized.wat
  tests/compiler/infer-array.untouched.wat
  tests/compiler/resolve-access.optimized.wat
  tests/compiler/resolve-access.untouched.wat
  tests/compiler/retain-release-sanity.optimized.wat
  tests/compiler/retain-release-sanity.untouched.wat
  tests/compiler/rt/flags.optimized.wat
  tests/compiler/rt/flags.ts
  tests/compiler/rt/flags.untouched.wat
  tests/compiler/std/array-access.optimized.wat
  tests/compiler/std/array-access.untouched.wat
  tests/compiler/std/array-literal.optimized.wat
  tests/compiler/std/array-literal.untouched.wat
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/array.ts
  tests/compiler/std/array.untouched.wat
  tests/compiler/std/arraybuffer.optimized.wat
  tests/compiler/std/arraybuffer.untouched.wat
  tests/compiler/std/map.optimized.wat
  tests/compiler/std/map.untouched.wat
  tests/compiler/std/set.optimized.wat
  tests/compiler/std/set.untouched.wat
  tests/compiler/std/static-array.optimized.wat
  tests/compiler/std/static-array.untouched.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/string.untouched.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/std/typedarray.untouched.wat
Labels: breaking change, std

#1143 Refactor loader. Now instantiate methods return ResultObject + extended exports
  lib/loader/index.d.ts
  lib/loader/index.js
  lib/loader/tests/index.js
  tests/bootstrap/index.ts
Labels: breaking change, tools
