Repository AssemblyScript/assemblyscript, pull requests merged in 2020-06, with the labels that each got.

#1322 Use node resolution in asinit-generated tsconfigs if possible
  .eslintrc.js
  bin/asinit
Labels: enhancement

#1321 Remember failed globals so we don't hit assertions
  src/common.ts
  src/compiler.ts
  src/diagnosticMessages.generated.ts
  src/diagnosticMessages.json
  src/flow.ts
  src/program.ts
  tests/compiler/variable-access-in-initializer.json
  tests/compiler/variable-access-in-initializer.ts
Labels: enhancement

#1332 chore: Set up semantic release
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
  scripts/postversion.js
Labels: enhancement

#1146 Use integer power for integer types
  src/common.ts
  src/compiler.ts
  src/glue/js/i64.d.ts
  src/glue/js/i64.js
  src/glue/wasm/i64.ts
  src/resolver.ts
  std/assembly/math.ts
  tests/compiler/binary.optimized.wat
  tests/compiler/binary.untouched.wat
  tests/compiler/resolve-binary.optimized.wat
  tests/compiler/resolve-binary.ts
  tests/compiler/resolve-binary.untouched.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/math.ts
  tests/compiler/std/math.untouched.wat
  tests/compiler/std/operator-overloading.optimized.wat
  tests/compiler/std/operator-overloading.untouched.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/string.untouched.wat
Labels: breaking change, enhancement

#1318 Make JS Target value 0 in enum and ASC_VERSION
  .eslintrc.js
  std/assembly/index.d.ts
  std/assembly/shared/target.ts
  std/portable/index.d.ts
  std/portable/index.js
  tests/compiler/asc-constants.untouched.wat
  tests/compiler/wasi/snapshot_preview1.untouched.wat
Labels: breaking change

#1279 modernize loader
  lib/loader/index.js
Labels: enhancement

#1335 chore: enlarge doc links in README
  README.md
Labels: enhancement, meta

#1339 refactor: Rename (dtoa|itoa)_stream to (dtoa|itoa)_buffered + simplify signature
  std/assembly/util/number.ts
  std/assembly/util/string.ts
  std/assembly/wasi/index.ts
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/array.untouched.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/std/typedarray.untouched.wat
  tests/compiler/wasi/trace.optimized.wat
  tests/compiler/wasi/trace.untouched.wat
Labels: enhancement

#1341 refactor(compiler): Modernize & refactoring some internal parts
  src/glue/binaryen.js
  src/glue/js/collections.js
  src/glue/js/float.js
  src/glue/js/i64.js
  src/glue/wasm/collections.ts
  src/glue/wasm/float.ts
  src/glue/wasm/i64.ts
  src/module.ts
Labels: enhancement

#1343 feat(asc): Add options merge algorithm for use by asconfig
  cli/asc.json
  cli/util/options.d.ts
  cli/util/options.js
  tests/cli/options.js
Labels: breaking change

#1349 Enforce strict field initialization
  src/ast.ts
  src/builtins.ts
  src/common.ts
  src/compiler.ts
  src/diagnosticMessages.generated.ts
  src/diagnosticMessages.json
  src/extra/ast.ts
  src/flow.ts
  src/parser.ts
  src/program.ts
  src/resolver.ts
  src/tokenizer.ts
  src/types.ts
  src/util/collections.ts
  tests/compiler/assert-nonnull.optimized.wat
  tests/compiler/assert-nonnull.untouched.wat
  tests/compiler/extends-baseaggregate.ts
  tests/compiler/field-initialization-errors.json
  tests/compiler/field-initialization-errors.ts
  tests/compiler/field-initialization-warnings.json
  tests/compiler/field-initialization-warnings.ts
  tests/compiler/field-initialization.json
  tests/compiler/field-initialization.optimized.wat
  tests/compiler/field-initialization.ts
  tests/compiler/field-initialization.untouched.wat
  tests/compiler/issues/1095.optimized.wat
  tests/compiler/issues/1095.untouched.wat
  tests/compiler/managed-cast.optimized.wat
  tests/compiler/managed-cast.untouched.wat
  tests/compiler/retain-release-sanity.ts
  tests/compiler/retain-release.ts
  tests/compiler/rt/finalize.ts
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/array.untouched.wat
  tests/compiler/std/symbol.optimized.wat
  tests/compiler/std/symbol.untouched.wat
Labels: breaking change
