Repository AssemblyScript/assemblyscript, pull requests merged in 2020-07, with the labels that each got.

#1368 Improve pass pipeline
  src/module.ts
  tests/compiler/binary.optimized.wat
  tests/compiler/class-overloading.optimized.wat
  tests/compiler/do.optimized.wat
  tests/compiler/extends-baseaggregate.optimized.wat
  tests/compiler/for.optimized.wat
  tests/compiler/implicit-getter-setter.optimized.wat
  tests/compiler/issues/1095.optimized.wat
  tests/compiler/issues/1225.optimized.wat
  tests/compiler/logical.optimized.wat
  tests/compiler/managed-cast.optimized.wat
  tests/compiler/number.optimized.wat
  tests/compiler/object-literal.optimized.wat
  tests/compiler/rc/local-init.optimized.wat
  tests/compiler/rc/logical-and-mismatch.optimized.wat
  tests/compiler/rc/logical-or-mismatch.optimized.wat
  tests/compiler/rc/optimize.optimized.wat
  tests/compiler/rc/rereturn.optimized.wat
  tests/compiler/rc/ternary-mismatch.optimized.wat
  tests/compiler/resolve-access.optimized.wat
  tests/compiler/resolve-binary.optimized.wat
  tests/compiler/resolve-elementaccess.optimized.wat
  tests/compiler/resolve-function-expression.optimized.wat
  tests/compiler/resolve-propertyaccess.optimized.wat
  tests/compiler/resolve-ternary.optimized.wat
  tests/compiler/resolve-unary.optimized.wat
  tests/compiler/retain-release-sanity.optimized.wat
  tests/compiler/retain-return.optimized.wat
  tests/compiler/rt/finalize.optimized.wat
  tests/compiler/runtime-full.optimized.wat
  tests/compiler/std/array-literal.optimized.wat
  tests/compiler/std/array.optimized.wat
  tests/compiler/std/arraybuffer.optimized.wat
  tests/compiler/std/dataview.optimized.wat
  tests/compiler/std/map.optimized.wat
  tests/compiler/std/math.optimized.wat
  tests/compiler/std/set.optimized.wat
  tests/compiler/std/staticarray.optimized.wat
  tests/compiler/std/string-casemapping.optimized.wat
  tests/compiler/std/string-encoding.optimized.wat
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/typedarray.optimized.wat
  tests/compiler/ternary.optimized.wat
  tests/compiler/ternary.ts
  tests/compiler/ternary.untouched.wat
  tests/compiler/while.optimized.wat
Labels: enhancement, performance

#1371 Support lazy global and function exports
  src/compiler.ts
  src/program.ts
  tests/compiler/exports-lazy.json
  tests/compiler/exports-lazy.optimized.wat
  tests/compiler/exports-lazy.ts
  tests/compiler/exports-lazy.untouched.wat
Labels: enhancement

#1378 fix: spec compliant parseInt
  std/assembly/number.ts
  std/assembly/util/string.ts
  tests/compiler/std/string.optimized.wat
  tests/compiler/std/string.ts
  tests/compiler/std/string.untouched.wat
Labels: bug, compatibility, enhancement, standard library

#1376 More parser & tokenizer refactorings
  src/diagnostics.ts
  src/parser.ts
  src/tokenizer.ts
Labels: enhancement, performance

#1383 Fixed Incorrect Callback Return in CLI Module Validation
  cli/asc.js
Labels: bug

#1238 Support asconfig.json
  .gitignore
  bin/asinit
  cli/asc.js
  cli/asc.json
  package.json
  tests/asconfig/complicated/asconfig.json
  tests/asconfig/complicated/assembly/index.ts
  tests/asconfig/complicated/package.json
  tests/asconfig/cyclical/asconfig.json
  tests/asconfig/cyclical/assembly/index.ts
  tests/asconfig/cyclical/extends.json
  tests/asconfig/cyclical/package.json
  tests/asconfig/entry-points/asconfig.json
  tests/asconfig/entry-points/assembly/globals.ts
  tests/asconfig/entry-points/assembly/index.ts
  tests/asconfig/entry-points/nested/asconfig.json
  tests/asconfig/entry-points/nested/assembly/index.ts
  tests/asconfig/entry-points/nested/package.json
  tests/asconfig/entry-points/package.json
  tests/asconfig/extends/asconfig.json
  tests/asconfig/extends/assembly/index.ts
  tests/asconfig/extends/extends.json
  tests/asconfig/extends/package.json
  tests/asconfig/index.js
  tests/asconfig/package.json
  tests/asconfig/respect-inheritence/asconfig.json
  tests/asconfig/respect-inheritence/assembly/index.ts
  tests/asconfig/respect-inheritence/package.json
  tests/asconfig/target/asconfig.json
  tests/asconfig/target/assembly/index.ts
  tests/asconfig/target/package.json
  tests/asconfig/use-consts/asconfig.json
  tests/asconfig/use-consts/assembly/index.ts
  tests/asconfig/use-consts/package.json
Labels: enhancement, tooling

#1319 Rename anyref to externref to match proposal change
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/builtins.ts
  src/common.ts
  src/compiler.ts
  src/flow.ts
  src/glue/binaryen.d.ts
  src/module.ts
  src/program.ts
  src/resolver.ts
  src/types.ts
  std/assembly/bindings/Reflect.ts
  std/assembly/bindings/console.ts
  std/assembly/index.d.ts
  std/assembly/reference.ts
  tests/compiler/features/reference-types.optimized.wat
  tests/compiler/features/reference-types.ts
  tests/compiler/features/reference-types.untouched.wat
  tests/features.json
Labels: breaking change

#1418 Simplify check condition for memcpy path in memmove
  std/assembly/util/memory.ts
  tests/compiler/extends-baseaggregate.untouched.wat
  tests/compiler/infer-array.untouched.wat
  tests/compiler/number.untouched.wat
  tests/compiler/object-literal.untouched.wat
  tests/compiler/resolve-access.untouched.wat
  tests/compiler/resolve-binary.untouched.wat
  tests/compiler/resolve-elementaccess.untouched.wat
  tests/compiler/resolve-ternary.untouched.wat
  tests/compiler/retain-release-sanity.untouched.wat
  tests/compiler/rt/finalize.untouched.wat
  tests/compiler/rt/stub-realloc.untouched.wat
  tests/compiler/std/array-literal.untouched.wat
  tests/compiler/std/array.untouched.wat
  tests/compiler/std/arraybuffer.untouched.wat
  tests/compiler/std/map.untouched.wat
  tests/compiler/std/pointer.untouched.wat
  tests/compiler/std/set.untouched.wat
  tests/compiler/std/static-array.untouched.wat
  tests/compiler/std/staticarray.untouched.wat
  tests/compiler/std/string-casemapping.untouched.wat
  tests/compiler/std/string-encoding.untouched.wat
  tests/compiler/std/string.untouched.wat
  tests/compiler/std/symbol.untouched.wat
  tests/compiler/std/typedarray.untouched.wat
  tests/compiler/wasi/trace.untouched.wat
Labels: enhancement, standard library
