Repository AssemblyScript/assemblyscript, pull requests merged in 2022-07, with the labels that each got.

#2350 fix: Add coercion for unsigned 64-bit types for bindings
  src/bindings/js.ts
  tests/compiler/bindings/esm.debug.d.ts
  tests/compiler/bindings/esm.debug.js
  tests/compiler/bindings/esm.debug.wat
  tests/compiler/bindings/esm.js
  tests/compiler/bindings/esm.release.d.ts
  tests/compiler/bindings/esm.release.js
  tests/compiler/bindings/esm.release.wat
  tests/compiler/bindings/esm.ts
  tests/compiler/bindings/raw.debug.d.ts
  tests/compiler/bindings/raw.debug.js
  tests/compiler/bindings/raw.debug.wat
  tests/compiler/bindings/raw.release.d.ts
  tests/compiler/bindings/raw.release.js
  tests/compiler/bindings/raw.release.wat
Labels: bug, enhancement, compatibility

#2344 fix: Add memory & table for esm binding's exports
  src/bindings/js.ts
  src/bindings/tsd.ts
  tests/compiler/bindings/esm.debug.d.ts
  tests/compiler/bindings/esm.debug.js
  tests/compiler/bindings/esm.release.d.ts
  tests/compiler/bindings/esm.release.js
  tests/compiler/bindings/raw.debug.d.ts
  tests/compiler/bindings/raw.release.d.ts
Labels: enhancement, tooling

#2361 Introduce more faster and memory optimal BitSet as replacment of Set<i32>
  src/compiler.ts
  src/flow.ts
  src/passes/findusedlocals.ts
  src/util/collections.ts
Labels: enhancement, performance

#2341 feat: add `--disableWarning` option to disable compilation warning
  cli/index.js
  cli/options.json
Labels: enhancement

#2336 feat: Add more document methods for bindings/dom.ts
  std/assembly/bindings/dom.ts
Labels: tooling, standard library, compatibility

#2370 Add fast-path for staticarray lowering if values is typedarray in bindings
  src/bindings/js.ts
  src/bindings/tsd.ts
  tests/compiler/bindings/esm.debug.d.ts
  tests/compiler/bindings/esm.debug.js
  tests/compiler/bindings/esm.debug.wat
  tests/compiler/bindings/esm.js
  tests/compiler/bindings/esm.release.d.ts
  tests/compiler/bindings/esm.release.js
  tests/compiler/bindings/esm.release.wat
  tests/compiler/bindings/esm.ts
  tests/compiler/bindings/raw.debug.d.ts
  tests/compiler/bindings/raw.debug.js
  tests/compiler/bindings/raw.debug.wat
  tests/compiler/bindings/raw.release.d.ts
  tests/compiler/bindings/raw.release.js
  tests/compiler/bindings/raw.release.wat
Labels: enhancement, performance, tooling

#2389 Update esbuild & typescript dependencies
  package-lock.json
  package.json
Labels: meta, dependencies

#2390 Improve valueof definitions. Add some extra tests
  std/assembly/index.d.ts
  tests/compiler/indexof-valueof.debug.wat
  tests/compiler/indexof-valueof.ts
Labels: enhancement
